### ISSUE TITLE
Error compiling the app

### ISSUE THREAD

**Issue by EliasMazz** [absimas/WhenVideosCollide#1]
I realy like the library and would like to help however I have a problem couldn't find "libvc.so"

The Full stack trace error can you help me?

Process: com.simas.vc, PID: 26861
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.simas.vc-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libvc.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:988)
            at com.simas.vc.VC.<clinit>(VC.java:17)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.Class.newInstance(Class.java:1606)
            at android.app.Instrumentation.newApplication(Instrumentation.java:1018)
            at android.app.Instrumentation.newApplication(Instrumentation.java:1003)
            at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4611)
            at android.app.ActivityThread.access$1500(ActivityThread.java:155)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5343)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by absimas** [comment]
`libvc.so` is not compiled by default. You need to build `ffmpeg` and then the `libvc` library. I've added steps explaining this process in the `README.md` file.
